// <auto-generated />
namespace The_Watcher.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ShoppingCartWishList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShoppingCartWishList));
        
        string IMigrationMetadata.Id
        {
            get { return "202208041640411_ShoppingCartWishList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
